[status]
disabled = false
pipestatus = true
symbol = "×"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold green)"
vicmd_symbol = "[❮](bold green)"

[c]
commands = [["clang", "--version"], ["gcc", "--version"], ["cc", "--version"]]
