bind 'set bell-style none' 2>/dev/null
bind 'set keyseq-timeout 1'

HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/bash/history"
mkdir -p "$(dirname "$HISTFILE")"

if command -v eza >/dev/null 2>&1; then
    alias ls='eza --group-directories-first --color=auto --icons=auto --git'
    alias ll='ls --long --header'
    alias la='ls --all'
    alias lla='ls --long --header --all'
    alias lt='ls --tree'
else
    alias ls='ls --color=auto'
    alias ll='ls -lh'
    alias la='ls -lha'
fi

function yy() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    command yazi "$@" --cwd-file="$tmp"
    IFS= read -r -d '' cwd < "$tmp"
    [ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd"
    command rm -f -- "$tmp"
}

# ble.sh
source -- ${XDG_DATA_HOME:-$HOME/.local/share}/blesh/ble.sh
