theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "error"

[editor.statusline]
right = ["diagnostics", "version-control", "selections", "position", "file-encoding"]

[keys.normal]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.space]
B = ":sh git blame -L %{cursor_line},+1 %{buffer_name} -p"

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
